export const ORDER_EVENT_TYPES = {
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_FIELD_CHANGED: 'ORDER_FIELD_CHANGED',
  ORDER_ITEM_ADDED: 'ORDER_ITEM_ADDED',
  ORDER_ITEM_QUANTITY_CHANGED: 'ORDER_ITEM_QUANTITY_CHANGED',
  ORDER_ITEM_REMOVED: 'ORDER_ITEM_REMOVED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_CLOSED: 'ORDER_CLOSED',
  ORDER_PAYMENT_UPDATED: 'ORDER_PAYMENT_UPDATED',
  ORDER_ACTION_EXECUTED: 'ORDER_ACTION_EXECUTED',
} as const;

